### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by chnasln** [SadraSamadi/people_counter#1]
hi, How are you ? 
Sorry for bothering you.

I use   python people_counter.py --prototxt mobilenet_ssd/MobileNetSSD_deploy.prototxt --model mobilenet_ssd/MobileNetSSD_deploy.caffemodel --input videos/example_02.mp4 --output output/output_02.avi   to run the program in anacon but it doesn't.

please can you help me ?

**Comment by saeventec** [comment]
Hi,
Can you show me the error, please?

**Comment by chnasln** [comment]
can you tell me when you're available
can you connect to my computer remotely

**Comment by chnasln** [comment]
usage: main.py [-h] -i INPUT -o OUTPUT [-p PROTOTXT] [-m MODEL]
               [-s SKIP_FRAMES] [-c CONFIDENCE] [-d DISTANCE]
main.py: error: the following arguments are required: -i/--input, -o/--output

**Comment by saeventec** [comment]
Sorry for the delay!
I've added a [Usage](https://github.com/SadraSamadi/people_counter#usage) section to the readme file, please follow the steps...
If you need more help please refer to the original article:
https://www.pyimagesearch.com/2018/08/13/opencv-people-counter/

**Comment by chnasln** [comment]
thanks for everything :)
it works in the video so can we run it on the webcam?

**Comment by saeventec** [comment]
Working with webcam is not available in this project.
You can use the article above.
Good luck...
